name: Terra R. Edenhart-Pepe
markdown: kramdown

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - R_Markdown_Midterm_Final 2.html
  -CPLNMarkdown.html
  -Betz_Pepe_Final.html
 
